### ISSUE TITLE
No timestamp.json being generated

### ISSUE THREAD

**Issue by focher** [zenyr/emit-timestamp-webpack-plugin#1]
I hesitate to open an issue on this, but when I follow the `readme` instructions I never actually have a `timestamp.json` file generated during the build process. I would like to get this first step working before I move on to using the file itself in my app.

My `npm run build` uses `rimraf dist && webpack --config config/webpack-prod.config.js --progress --profile --bail` as the command line.

I have checked and double-checked my `webpack-common.config.js` which is included within `webpack.config.js` through:

 `const commonConfig = require('./config/webpack-common.config.js');`

It doesn't generate any errors. Has anyone else ever reported this problem?

**Comment by zenyr** [comment]
Hmm, maybe because there are at least 2 major webpack versions out there. I've not been using mine either. 
It used to work fine back in days, but it surely won't work out of the box in these days.

I may look into this someday, probably with `Webpack2`.

**Comment by zenyr** [comment]
Just tried the plugin with `webpack@1` without much problem. Are you on `webpack@2`?. 
```
$ ./node_modules/.bin/webpack src/index.js build/bundle.js
EmitTimestampPlugin - Emit N/A
Hash: 52c24447844c29eb5c2c
Version: webpack 1.14.0
Time: 70ms
         Asset       Size  Chunks             Chunk Names
     bundle.js    1.52 kB       0  [emitted]  main
timestamp.json  369 bytes          [emitted]
   [0] ./src/index.js 133 bytes {0} [built]
✨  Done in 0.41s.
```

**Comment by zenyr** [comment]
Huh, weird. The plugin is working.. somewhat fine even with `webpack@2 in my end. 

added a test project in 'test-webpack2' folder (with npm link feature) which works just as expected.

I appreciate your voice. Let me close this issue for now but please let me know if this issue still happens!
